# Generated by Django 2.1.1 on 2018-09-22 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='position_title',
            new_name='title',
        ),
    ]
