# Generated by Django 2.1.1 on 2018-09-24 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20180924_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='title',
            new_name='position_title',
        ),
    ]
